### ISSUE TITLE
Long Reads only

### ISSUE THREAD

**Issue by ashokpatowary** [Xinglab/lr2rmats#11]
Hi @yangao07 

Is there any chance that you will be having a version of lr2mats which only requires long-read data as input and not the supporting short reads?

Thanks

**Comment by yangao07** [comment]
If you run `./bin/lr2rmats` you will see that `lr2rmats` does have a sub-command called `bam2gtf`.
It takes a sam/bam file as input and outputs the transcripts derived from the alignment result in GTF format.

**Comment by ashokpatowary** [comment]
Hi I @yangao07 

Thanks for your response. I am having a follow-up query. Am sorry, if I am missing something. So, the gft file generated will not having any information about know genes. So, how should I proceed with the gtf file? What I understand I should not follow `snakemake`; but follow `lr2mats` subcomands `bam2gtf` `bam2sj` `update-gtf`. Did I understand correct?

**Comment by yangao07** [comment]
I think you first need to clarify what you have (input), and what you want (output).
Basically, the lr2rmats has all the subcommand to fulfill the function as described in snakemake.
To only work with long-read data, you do need to manually run these subcommands instead of snakemake.

**Comment by ashokpatowary** [comment]
I am having PacBio iso-seq log-read files from multiple samples. I want to look for differential splicing in between the  samples. My input is sam/bam file generated by minimap2.

Thanks

**Comment by yangao07** [comment]
With lr2rmats, I don't think you can perform AS analysis without short-read data.
You can generate a GTF file from each BAM, then within this GTF, you will have some `known` and `novel` transcript. 
I think the numbers and the structure of the `novel` transcript are something you can compare between samples.

**Comment by ashokpatowary** [comment]
Thanks @yangao07
