### ISSUE TITLE
duplicate items in samp1.known.gtf

### ISSUE THREAD

**Issue by zpliu1126** [Xinglab/lr2rmats#12]
I run this Program with  successful and test with only one  sample. But there are some duplicate items in the output file `samp1.known.gtf`. 
is it normal？

![image](https://user-images.githubusercontent.com/39325949/89420942-00e70e80-d766-11ea-94ff-de8ddb90d4d0.png)

And I also have a question about the input data 。

if I have replicattion of short read data in a sample ，how can I use them at the same time。or just use one replicate is ok。
```bash
sample:
    long_read:
        samp1: PacBio.fa 

    short_read: # if short-read is single-end, just leave `second` empty, like `second: [] `
        samp1: 
            first: replicate1_1.fq
            second: replicate2_2.fq
```

**Comment by yangao07** [comment]
Not sure how these duplicates come. Did you check your bam file? Are there also duplicates?

For multiple replicates, you can simply merge them together into one file and put it after 'first:'.

**Comment by zpliu1126** [comment]
Thank you for your reply. I find there are  duplicate item in long read file。

And in order to use replicates short reads; my config file looks like that:

```bash
sample:
    long_read:
        samp1: PacBio.fa 
        samp2: PacBio.fa 
    short_read: # if short-read is single-end, just leave `second` empty, like `second: [] `
        samp1: 
            first: replicate1_1.fastq 
            second: replicate1_2.fastq   
        samp2: 
            first: replicate2_1.fastq 
            second: replicate2_2.fastq 
```
could it work ?

**Comment by yangao07** [comment]
It should work, and you will get two output files.

**Comment by zpliu1126** [comment]
yes, I got the sample1 files and smaple2 files.
And if the `update.gtf` used  the replicate short reads message。 Just same as  
> merge replicate files together into one file
