### ISSUE TITLE
Snakefile 文件中，star_idx的输出目录，需要采用directory 申明

### ISSUE THREAD

**Issue by ZhangQiuxue** [Xinglab/lr2rmats#2]
采用最新版本的Snakemake ,如果rule 中输出的是目录，需要采用directory 进行申明。
在Snakefile 中的 rule star_idx 部分（第10行）， 输出目录 `config["genome"]["star_idx"] ` 需要用directory 申明。 如下：
```
 directory(config["genome"]["star_idx"])
```

**Comment by yangao07** [comment]
Thanks!
Now there are two `Snakefile` for old (<5.2.0) and new(>=5.2.0) version of snakemake.

Yan
