### ISSUE TITLE
How to set the parameter "rm_gtf" when there is no rRNA annotation file?

### ISSUE THREAD

**Issue by linglingtingfei** [Xinglab/lr2rmats#7]
Hi @yangao07,
I have no rRNA annotation file,  so I edit "config.yaml" file with nothing on the parameter "rm_gtf". But it came across some error. I removed the parameter "rm_gtf", another issue happened. I want to know How to set the parameter "rm_gtf" when there is no rRNA annotation file?
 
Thank you!
ling

**Comment by yangao07** [comment]
This error has been fixed in b8b3cfe.
