### ISSUE TITLE
I have not short reads, only have long ONT reads, how could I use this tools?

### ISSUE THREAD

**Issue by hygine** [Xinglab/lr2rmats#9]
I have not short reads, only have long ONT reads, how could I use this tools? thanks.

**Comment by hygine** [comment]
@yangao07

**Comment by yangao07** [comment]
I am afraid not. 
Lr2rmats requires both long-read and short-read data as input.
We may have a new version which only requires long-read data as input, but it won't happen soon, unfortunately.
